server:
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  messages:
    basename: error




file:
  dir: D:/board
