spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TEST
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: create