server:
  servlet:
    session:
      tracking-modes: cookie


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TEST
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  messages:
    basename: error


file:
  dir: D:/board
