server:
  servlet:
    session:
      tracking-modes: cookie


spring:
  profiles:
    active: ${profile:prod}

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  messages:
    basename: error

file:
  dir: D:/board

